before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: NS2d1QVu4mUFPciimMn+SS/lRRpx76vwPLiKzjPBHAEy/phFRS/nSDDbrIOqUn/kSVJIqhziRpRer2rydj3d1eBxPJFD7ue2ONHQ/Hkx4aI39jZy8jHoaLpBbveg229Gc9trPfh6C1FSIevqn3q2dEtLbg50NjcQOmBYcMMbsKf/hLya3mC01WpA56VkMdXT6eKFuDpK0+x591Kk1oP4mH/S2E3kkTKfYF0er7207r9QBAXZNDCmKeza9b3HPBR8/IwIv1ZyVaBh91sF3jMNayRKQmcHTxijGr5CfZMSyYFmjkUqqxvz7PjY1CBGe7RHVSE/Z4QFj2Xi0WBUJjHpz9t6Cbzj7Kd45VQH5xfOJGmbi/mCDdZ/4jBHtXeLN/MUYYb7f4ow9gGB6ZKhUVIwnmMc4wc2GyZxTNdeMPlqLNc9eFtUr46/hKUF+rElOdi3b52vDTwHWhOSc7+i+CmWsViOpdYVwh1QrVl+lEPJrqH78H+xDqWBB99m6rftb0TV3rcEss030FerHqHYADpf33G7fANfeBlOVZOLEyZTmISBgKruGf/WseNC05lZ9C+kEyaFLkPQ6zRAa1/ikrUPXrmsAFkn6KWtRPTBD6jkAoxv8zEEbF3ujGy+nE42Nhmz3CqwCol+3D1tanYAv2lRpyEMl0ONELSd/ovLJtWnRq0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
